import type { CivicInsight, HotspotPrediction, TrendMetric } from '@/lib/types/analytics';
import type { Issue } from '@/lib/types/issue';
import type { UserProfile } from '@/lib/types/user';
const now = new Date(); const iso = (hoursAgo: number) => new Date(now.getTime() - hoursAgo * 3600000).toISOString();
export const mockIssues: Issue[] = [
  { id: 'iss-pothole-4821', title: 'Large pothole at school crossing', description: 'Deep pothole is forcing two-wheelers into the bus lane during morning school traffic.', category: 'POTHOLE', subcategory: 'road_surface_damage', severity: 8, images: ['https://images.unsplash.com/photo-1573869902561-0908ca9d98b4?auto=format&fit=crop&w=1200&q=80'], thumbnailUrl: 'https://images.unsplash.com/photo-1573869902561-0908ca9d98b4?auto=format&fit=crop&w=600&q=80', location: { lat: 12.9716, lng: 77.5946, address: 'MG Road school crossing', ward: 'Ward 12', geohash: 'tdr1wx' }, status: 'VERIFIED', statusHistory: [{ status: 'REPORTED', at: iso(30), by: 'Asha Rao', note: 'AI classified and routed.' }, { status: 'VERIFIED', at: iso(18), by: 'Community', note: '10 neighbors verified.' }], assignedTo: null, department: 'Public Works', slaDeadline: new Date(now.getTime() + 18 * 3600000).toISOString(), escalationLevel: 1, reportedBy: 'user-asha', reportedByName: 'Asha Rao', reportedAt: iso(30), verifiedBy: ['u1','u2','u3','u4','u5','u6','u7','u8','u9','u10','u11'], verificationCount: 11, upvotes: 42, upvotedBy: [], comments: [{ id: 'c1', authorId: 'u2', authorName: 'Rahul', body: 'This is getting worse after the rain.', createdAt: iso(12), sentiment: 0.72 }], aiAnalysis: { isIssue: true, confidence: 0.94, suggestedTitle: 'Large pothole at school crossing', suggestedDescription: 'Hazardous road surface damage near pedestrian crossing.', suggestedCategory: 'POTHOLE', suggestedSubcategory: 'road_surface_damage', suggestedDepartment: 'Public Works', suggestedSeverity: 8, detectedObjects: ['pothole','road','crossing'], safetyAssessment: 'high', reasoning: 'Visible road cavity in active travel path.', communityAngerScore: 81, issueDna: 'Third pothole report in this corridor in 45 days. Root cause likely recurring drainage overflow weakening the road base.' }, predictedRisk: 0.78 },
  { id: 'iss-water-1930', title: 'Water leak near community clinic', description: 'Continuous leak is pooling near the entrance and making the sidewalk slippery.', category: 'WATER', subcategory: 'pipe_leak', severity: 7, images: ['https://images.unsplash.com/photo-1584467541268-b040f83be3fd?auto=format&fit=crop&w=1200&q=80'], thumbnailUrl: 'https://images.unsplash.com/photo-1584467541268-b040f83be3fd?auto=format&fit=crop&w=600&q=80', location: { lat: 12.9822, lng: 77.6041, address: 'Indiranagar clinic road', ward: 'Ward 18', geohash: 'tdr3p1' }, status: 'ASSIGNED', statusHistory: [{ status: 'REPORTED', at: iso(22), by: 'Imran Khan', note: 'Reported by voice mode.' }, { status: 'ASSIGNED', at: iso(5), by: 'Water Department', note: 'Field crew assigned.' }], assignedTo: 'crew-water-2', department: 'Water Department', slaDeadline: new Date(now.getTime() + 7 * 3600000).toISOString(), escalationLevel: 0, reportedBy: 'user-imran', reportedByName: 'Imran Khan', reportedAt: iso(22), verifiedBy: ['u2','u5','u8','u9'], verificationCount: 4, upvotes: 18, upvotedBy: [], comments: [], aiAnalysis: { isIssue: true, confidence: 0.9, suggestedTitle: 'Water leak near community clinic', suggestedDescription: 'Standing water and possible pipe leak near healthcare access point.', suggestedCategory: 'WATER', suggestedSubcategory: 'pipe_leak', suggestedDepartment: 'Water Department', suggestedSeverity: 7, detectedObjects: ['water','sidewalk'], safetyAssessment: 'medium', reasoning: 'Pooling water creates slip hazard and water loss.', communityAngerScore: 58 }, predictedRisk: 0.66 },
  { id: 'iss-light-7740', title: 'Streetlights out on park edge', description: 'Three consecutive streetlights are out, making the evening walking path unsafe.', category: 'LIGHTING', subcategory: 'streetlight_outage', severity: 6, images: ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80'], thumbnailUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80', location: { lat: 12.9651, lng: 77.6083, address: 'Cubbon Park east gate', ward: 'Ward 12', geohash: 'tdr1yy' }, status: 'IN_PROGRESS', statusHistory: [{ status: 'REPORTED', at: iso(54), by: 'Meera Nair', note: 'AI routed to lighting team.' }, { status: 'IN_PROGRESS', at: iso(8), by: 'Power & Lighting', note: 'Repair truck checked in.' }], assignedTo: 'crew-light-5', department: 'Power & Lighting', slaDeadline: new Date(now.getTime() - 4 * 3600000).toISOString(), escalationLevel: 1, reportedBy: 'user-meera', reportedByName: 'Meera Nair', reportedAt: iso(54), verifiedBy: ['u1','u3','u7','u11','u12','u13'], verificationCount: 6, upvotes: 27, upvotedBy: [], comments: [], aiAnalysis: { isIssue: true, confidence: 0.86, suggestedTitle: 'Streetlights out on park edge', suggestedDescription: 'Lighting outage in pedestrian safety corridor.', suggestedCategory: 'LIGHTING', suggestedSubcategory: 'streetlight_outage', suggestedDepartment: 'Power & Lighting', suggestedSeverity: 6, detectedObjects: ['streetlight','park path'], safetyAssessment: 'medium', reasoning: 'Repeated outage pattern near public park.', communityAngerScore: 63 }, predictedRisk: 0.61 },
  { id: 'iss-waste-2207', title: 'Overflowing waste point behind market', description: 'Waste has overflowed into the lane and stray animals are scattering it.', category: 'WASTE', subcategory: 'overflowing_bin', severity: 5, images: ['https://images.unsplash.com/photo-1604187351574-c75ca79f5807?auto=format&fit=crop&w=1200&q=80'], thumbnailUrl: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?auto=format&fit=crop&w=600&q=80', location: { lat: 12.9584, lng: 77.5831, address: 'KR Market rear lane', ward: 'Ward 9', geohash: 'tdr1mm' }, status: 'RESOLVED', statusHistory: [{ status: 'REPORTED', at: iso(72), by: 'Dev Patel', note: 'Reported with photo.' }, { status: 'RESOLVED', at: iso(9), by: 'Sanitation', note: 'Crew cleared lane; resolution photo verified.' }], assignedTo: 'crew-sanitation-1', department: 'Sanitation', slaDeadline: iso(36), escalationLevel: 0, reportedBy: 'user-dev', reportedByName: 'Dev Patel', reportedAt: iso(72), verifiedBy: ['u4','u5','u6'], verificationCount: 3, upvotes: 13, upvotedBy: [], comments: [], aiAnalysis: { isIssue: true, confidence: 0.91, suggestedTitle: 'Overflowing waste point behind market', suggestedDescription: 'Overflowing waste point affecting market access lane.', suggestedCategory: 'WASTE', suggestedSubcategory: 'overflowing_bin', suggestedDepartment: 'Sanitation', suggestedSeverity: 5, detectedObjects: ['trash','lane'], safetyAssessment: 'low', reasoning: 'Sanitation issue visible with public health impact.', communityAngerScore: 44, issueDna: 'Overflow correlated with weekend market load. Better bin placement and pickup timing could prevent recurrence.' }, predictedRisk: 0.33 }
];
export const mockUsers: UserProfile[] = [
  { id: 'user-asha', name: 'Asha Rao', email: 'asha@example.com', ward: 'Ward 12', role: 'citizen', points: 1260, level: 5, badges: [{ id: 'first-report', name: 'First Signal', earnedAt: iso(200) }], reportsFiled: 17, verifications: 44, resolvedHelp: 9 },
  { id: 'user-imran', name: 'Imran Khan', email: 'imran@example.com', ward: 'Ward 18', role: 'citizen', points: 980, level: 4, badges: [], reportsFiled: 12, verifications: 31, resolvedHelp: 4 },
  { id: 'admin-ward', name: 'Ward Admin', email: 'admin@example.com', ward: 'Citywide', role: 'admin', points: 0, level: 1, badges: [], reportsFiled: 0, verifications: 0, resolvedHelp: 0 }
];
export const trendData: TrendMetric[] = [ { date: 'Mon', reported: 18, resolved: 9 }, { date: 'Tue', reported: 24, resolved: 12 }, { date: 'Wed', reported: 21, resolved: 15 }, { date: 'Thu', reported: 33, resolved: 18 }, { date: 'Fri', reported: 28, resolved: 24 }, { date: 'Sat', reported: 19, resolved: 17 }, { date: 'Sun', reported: 15, resolved: 20 } ];
export const mockHotspots: HotspotPrediction[] = [ { id: 'hot-1', lat: 12.971, lng: 77.598, ward: 'Ward 12', category: 'POTHOLE', risk: 84, explanation: 'Rainfall plus repeated road reports indicate new road-surface failures likely next week.' }, { id: 'hot-2', lat: 12.984, lng: 77.603, ward: 'Ward 18', category: 'WATER', risk: 72, explanation: 'Cluster of water complaints suggests pressure leak migration.' }, { id: 'hot-3', lat: 12.959, lng: 77.584, ward: 'Ward 9', category: 'WASTE', risk: 61, explanation: 'Market activity spike is likely to overload bins after the weekend.' } ];
export const mockInsight: CivicInsight = { id: 'insight-weekly', title: 'AI Insight of the Week', summary: 'Ward 12 is the fastest-growing risk area, mostly because road damage and lighting failures overlap around pedestrian routes.', recommendations: ['Pre-position one public works crew near MG Road before monsoon showers.', 'Audit streetlight feeder boxes along the park edge.', 'Notify Ward 12 citizens when repair crews check in.'], generatedAt: iso(2), confidence: 0.87, hotspots: mockHotspots };
